name: Build Executable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build raspsim Executable
        run: make -j$(nproc) raspsim
      
      - name: Upload raspsim Executable
        uses: actions/upload-artifact@v4
        with:
          name: raspsim
          path: raspsim
